# Generated by Django 4.1.7 on 2023-03-07 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItem',
            new_name='Items',
        ),
    ]
