# Generated by Django 4.1.7 on 2023-03-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_account_accounts_rename_listitem_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='buyerId',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sellerId',
        ),
        migrations.DeleteModel(
            name='LogItem',
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
