# Generated by Django 4.1.7 on 2023-02-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='startingPrice',
            new_name='price',
        ),
    ]
