# Generated by Django 4.1.7 on 2023-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_startingprice_listitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('soldDateTime', models.DateTimeField(verbose_name='Date/Time Logged')),
            ],
        ),
    ]
