# Generated by Django 4.1.7 on 2023-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_listitem_name_alter_logitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
