# Generated by Django 4.1.7 on 2023-03-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='sold',
            field=models.BooleanField(default=True),
        ),
    ]
