# Generated by Django 4.1.7 on 2023-03-07 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_logitem_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('postageCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidIncrement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('partsOnly', 'Parts Only')], max_length=20)),
                ('endDateTime', models.DateTimeField(verbose_name='Date/Time Logged')),
                ('acceptReturns', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=1000)),
                ('numBids', models.IntegerField(default=0)),
                ('sold', models.BooleanField(default=False)),
                ('buyerId', models.CharField(default='placeholder', max_length=40)),
                ('sellerId', models.CharField(default='placeholder', max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='LogItem',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
