# Generated by Django 4.1.7 on 2023-03-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_endeditems_destinationaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeditems',
            name='acceptReturns',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='buyerId',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='destinationAddress',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='numBids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='sellerId',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='sold',
            field=models.BooleanField(),
        ),
    ]
