# Generated by Django 4.1.7 on 2023-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_alter_endeditems_acceptreturns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeditems',
            name='buyerId',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='destinationAddress',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
