# Generated by Django 4.1.7 on 2023-03-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='buyerId',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sellerId',
        ),
        migrations.DeleteModel(
            name='LogItem',
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
