# Generated by Django 4.1.7 on 2023-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_endeditems_buyerid_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='minBalance'),
        ),
    ]
