# Generated by Django 4.1.7 on 2023-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_accounts_minbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='endeditems',
            name='bidders',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='bidders',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
    ]
