# Generated by Django 4.1.7 on 2023-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_endeditems_name_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeditems',
            name='bidders',
            field=models.CharField(default='[]', max_length=999999999),
        ),
        migrations.AlterField(
            model_name='items',
            name='bidders',
            field=models.CharField(default='[]', max_length=999999999),
        ),
    ]
