# Generated by Django 4.1.7 on 2023-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_endeditems_bidders_alter_items_bidders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeditems',
            name='buyerId',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='sellerId',
            field=models.IntegerField(max_length=40),
        ),
    ]
