# Generated by Django 4.1.7 on 2023-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_endeditems_buyerid_alter_endeditems_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endeditems',
            name='buyerId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endeditems',
            name='sellerId',
            field=models.IntegerField(),
        ),
    ]
