# Generated by Django 4.1.7 on 2023-03-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_accounts_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
