# Generated by Django 4.1.7 on 2023-04-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_delete_logmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endeditems',
            old_name='salePrice',
            new_name='price',
        ),
    ]
