# Generated by Django 4.1.7 on 2023-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_saleprice_endeditems_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndedItems',
        ),
        migrations.AddField(
            model_name='items',
            name='destinationAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='transactionSuccess',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
