# Generated by Django 4.1.7 on 2023-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_buyerid_items_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('bOIS', 'Business, Office & Industrial Supplies'), ('hB', 'Health & Beauty'), ('f', 'Fashion'), ('e', 'Electronics'), ('hG', 'Home Garden'), ('sHL', 'Sports, Hobbies & Leisure'), ('mt', 'Motors'), ('cA', 'Collectables & Art'), ('mda', 'Media'), ('o', 'other')], default='e', max_length=50),
        ),
    ]
