# Generated by Django 4.1.7 on 2023-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='imageName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
