# Generated by Django 4.1.7 on 2023-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_items_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='imageName',
            field=models.CharField(max_length=100),
        ),
    ]
