# Generated by Django 4.1.7 on 2023-04-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_items_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='imageName',
        ),
    ]
