# Generated by Django 4.1.7 on 2023-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_rename_posterurl_movie_posterurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
