# Generated by Django 4.1.7 on 2023-04-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('yearOfRelease', models.CharField(max_length=4)),
                ('runtime', models.CharField(max_length=5)),
                ('rating', models.CharField(max_length=5)),
                ('votes', models.CharField(max_length=300)),
                ('gross', models.CharField(max_length=300)),
                ('posterURL', models.CharField(max_length=300)),
            ],
        ),
    ]
