# Generated by Django 4.1.7 on 2023-05-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='summary',
        ),
    ]
