# Generated by Django 4.1.7 on 2023-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_rename_description_movie_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gross',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yearOfRelease',
            field=models.IntegerField(),
        ),
    ]
