# Generated by Django 4.1.7 on 2023-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_movie_gross_movie_director_movie_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDb',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('yearOfRelease', models.IntegerField()),
                ('ageRating', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('votes', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('genres', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('stars', models.CharField(max_length=300)),
                ('runtime', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('aspectRatio', models.CharField(max_length=20)),
                ('posterURL', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
