# Generated by Django 4.1.7 on 2023-05-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_imdb_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdb',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='imdb',
            old_name='writer',
            new_name='writers',
        ),
    ]
