# Generated by Django 4.1.7 on 2023-05-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_rename_director_imdb_directors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdb',
            old_name='ageRating',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='imdb',
            old_name='yearOfRelease',
            new_name='year',
        ),
    ]
