# Generated by Django 4.1.7 on 2023-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_rename_agerating_imdb_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
