# Generated by Django 4.1.7 on 2023-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_item_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
