# Generated by Django 4.1.7 on 2023-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='aspectRatio',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
