# Generated by Django 4.1.7 on 2023-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_imdb_aspectratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='directors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='writers',
            field=models.CharField(max_length=500),
        ),
    ]
