# Generated by Django 4.1.7 on 2023-05-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_item_bidincrement_alter_item_postagecost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdb',
            old_name='posterURL',
            new_name='posterUrl',
        ),
    ]
